.compile_template: &compile_definition
  tags:
    - docker
  script:
    - latexmk -pdf examples/letter
  stage: build
  artifacts:
    paths:
      - "*.pdf"

compile:texlive2023:
  image: sergiud/texlive:2023
  <<: *compile_definition
